from datetime  import datetime
from pathlib   import Path

TOPIC_ICONS = {
    "Kollywood cinema":      "🎬",
    "Hollywood movies":      "🎥",
    "Tamil Nadu politics":   "🏛️",
    "Artificial Intelligence": "🤖",
    "India startups":        "🚀",
}

OUTPUT_DIR = Path(__file__).parent.parent / "output"


class DigestAgent:
    """
    Takes weather + humor-rewritten news and builds a clean HTML email digest.
    Also saves a Markdown version to output/latest_digest.md
    """

    def run(
        self,
        weather:       dict,
        humor_output:  dict,
        recipient_name: str = "Friend",
    ) -> str:
        """Returns the HTML body string for the email."""

        today         = datetime.now().strftime("%A, %d %B %Y")
        weather_funny = humor_output["weather_funny"]
        news          = humor_output["news"]

        # ── Build HTML ──────────────────────────────────────────────
        sections_html = ""
        sections_md   = ""

        for topic, articles in news.items():
            if not articles:
                continue

            icon = TOPIC_ICONS.get(topic, "📰")
            sections_html += f"""
            <div class="section">
              <h2>{icon} {topic}</h2>
            """
            sections_md += f"\n## {icon} {topic}\n"

            for art in articles:
                funny   = art.get("funny", art.get("context", art.get("summary", "")))
                link    = art.get("link", "#")
                title   = art.get("title", "")
                sections_html += f"""
              <div class="article">
                <p class="funny">{funny}</p>
                <p class="source"><a href="{link}">📎 {title[:80]}</a></p>
              </div>
            """
                sections_md += f"\n**{title}**\n{funny}\n[Read]({link})\n"

            sections_html += "</div>"

        html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body        {{ font-family: 'Segoe UI', Arial, sans-serif; background:#f5f5f5; margin:0; padding:20px; }}
  .card       {{ background:#fff; border-radius:12px; max-width:640px; margin:0 auto;
                 padding:32px; box-shadow:0 2px 12px rgba(0,0,0,.08); }}
  h1          {{ font-size:22px; color:#1a1a1a; margin-bottom:4px; }}
  .date       {{ color:#888; font-size:13px; margin-bottom:24px; }}
  .weather    {{ background:#fff8e6; border-radius:8px; padding:16px; margin-bottom:24px;
                 border-left:4px solid #f5a623; }}
  .weather h2 {{ margin:0 0 8px; font-size:16px; color:#c47a00; }}
  .weather p  {{ margin:0; color:#555; line-height:1.6; }}
  h2          {{ font-size:17px; color:#333; margin:24px 0 12px; }}
  .article    {{ border-bottom:1px solid #f0f0f0; padding-bottom:14px; margin-bottom:14px; }}
  .funny      {{ color:#222; line-height:1.7; margin:0 0 6px; }}
  .source     {{ margin:0; }}
  .source a   {{ color:#1a73e8; font-size:12px; text-decoration:none; }}
  .footer     {{ margin-top:32px; text-align:center; color:#bbb; font-size:11px; }}
  .section    {{ margin-bottom:24px; }}
</style>
</head>
<body>
<div class="card">

  <h1>☀️ Good Morning, {recipient_name}!</h1>
  <div class="date">{today}</div>

  <div class="weather">
    <h2>🌡️ {weather.get('city','Salem')} Weather</h2>
    <p>{weather_funny}</p>
    <p style="font-size:12px;color:#aaa;margin-top:8px;">
      {weather.get('temp_c')}°C &nbsp;|&nbsp;
      Humidity {weather.get('humidity')}% &nbsp;|&nbsp;
      Rain {weather.get('rain_chance')}% &nbsp;|&nbsp;
      Wind {weather.get('wind_kmh')} km/h
    </p>
  </div>

  {sections_html}

  <div class="footer">
    Generated by your AI Daily Newsroom 🤖 &nbsp;·&nbsp; {today}
  </div>

</div>
</body>
</html>"""

        # ── Save Markdown ────────────────────────────────────────────
        OUTPUT_DIR.mkdir(exist_ok=True)
        md_path = OUTPUT_DIR / "latest_digest.md"
        md_content = f"# ☀️ Good Morning, {recipient_name}!\n_{today}_\n\n"
        md_content += f"## 🌡️ Weather — {weather.get('city','Salem')}\n{weather_funny}\n"
        md_content += sections_md
        md_path.write_text(md_content)
        print(f"[DigestAgent] Digest saved to {md_path}")

        return html